export const carsList = [
   {
      id: 1,
      name: 'Honda Civic 2007 року',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/akoqdbfnr6ya3-UA/image;s=516x361',
      price: 6990,
      year: 2007,
      typeTransport: 'Легкові',
      typeBody: 'Хетчбек',
      brand: 'Honda',
      mileage: '290 тис.',
   },
   {
      id: 2,
      name: 'Mazda cx-5 2015 року',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/vmvzxd3iqfu41-UA/image;s=516x361',
      price: 15800,
      year: 2015,
      typeTransport: 'Легкові',
      typeBody: 'Позашляховик / Кроссовер',
      brand: 'Mazda',
      mileage: '84 тис.',
   },
   {
      id: 3,
      name: 'Peugeot 207 2008рік розмитнений',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/o7t0p6xn6ine2-UA/image;s=516x361',
      price: 3600,
      year: 2008,
      typeTransport: 'Легкові',
      typeBody: 'Хетчбек',
      brand: 'Peugeot',
      mileage: '120 тис.',
   },
   {
      id: 4,
      name: 'Продам Lexus rx 300 2003г',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/l91irazohag4-UA/image;s=516x361',
      price: 8300,
      year: 2003,
      typeTransport: 'Легкові',
      typeBody: 'Позашляховик / Кроссовер',
      brand: 'Lexus',
      mileage: '180 тис.',
   },
   {
      id: 5,
      name: 'NISSAN Qashgai Tekna 360',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/800wndfztr1v2-UA/image;s=516x361',
      price: 14950,
      year: 2014,
      typeTransport: 'Легкові',
      typeBody: 'Позашляховик / Кроссовер',
      brand: 'Nissan',
      mileage: '180 тис.',
   },
   {
      id: 6,
      name: 'IVECO eurocargo 120E22 EURO-5',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/1ghq9uztp42e2-UA/image;s=516x361',
      price: 22000,
      year: 2010,
      typeTransport: 'Вантажні',
      typeBody: 'Ізотермічний кузов',
      brand: 'IVECO',
      mileage: '400 тис.',
   },
   {
      id: 7,
      name: 'Renault Master 2007',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/322ig64bnah52-UA/image;s=1000x700',
      price: 7400,
      year: 2007,
      typeTransport: 'Вантажні',
      typeBody: 'Фургон',
      brand: 'Renault',
      mileage: '300 тис.',
   },
   {
      id: 8,
      name: 'Renault Maxity Master Movano Midlum',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/j8eakramaix22-UA/image;s=516x361',
      price: 10750,
      year: 2010,
      typeTransport: 'Вантажні',
      typeBody: 'Ізотермічний кузов',
      brand: 'Renault',
      mileage: '220 тис.',
   },
   {
      id: 9,
      name: 'Богдан DF-40 3,9 турбо',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/ijbj9alem83x-UA/image;s=1000x700',
      price: 3600,
      year: 2007,
      typeTransport: 'Вантажні',
      typeBody: 'Бортова вантажівка',
      brand: 'Богдан',
      mileage: '217 тис.',
   },
   {
      id: 10,
      name: 'Спрінтер 416 в гарному стані SPRINTER',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/gla4h93ud72b2-UA/image;s=1000x700',
      price: 12700,
      year: 2003,
      typeTransport: 'Вантажні',
      typeBody: 'Фургон',
      brand: 'Mercedes',
      mileage: '276 тис.',
   },
   {
      id: 11,
      name: 'Renault master 3',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/9xxcxcskk7fx-UA/image;s=1000x700',
      price: 15800,
      year: 2018,
      typeTransport: 'Вантажні',
      typeBody: 'Фургон',
      brand: 'Renault',
      mileage: '200 тис.',
   },
   {
      id: 12,
      name: 'Ман TGX iдеальний стан',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/q1pe9a83nthi2-UA/image;s=1000x700',
      price: 24900,
      year: 2015,
      typeTransport: 'Вантажні',
      typeBody: 'Самоскид',
      brand: 'MAN',
      mileage: '830 тис.',
   },
   {
      id: 13,
      name: 'Mercedes 513 2010 р.',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/71lqx4jst8kg-UA/image;s=1000x700',
      price: 18000,
      year: 2010,
      typeTransport: 'Вантажні',
      typeBody: 'Інші',
      brand: 'Mercedes',
      mileage: '83 тис.',
   },
   {
      id: 14,
      name: 'Рейсовий стан Рено Мастер,Один власник',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/wyqtkdmc5vhy2-UA/image;s=1000x700',
      price: 10200,
      year: 2014,
      typeTransport: 'Вантажні',
      typeBody: 'Бортова вантажівка',
      brand: 'Renault',
      mileage: '780 тис.',
   },
   {
      id: 15,
      name: 'MAN TGE 2020 автомат та гідроборт',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/ucv9q8crjf902-UA/image;s=1000x700',
      price: 24300,
      year: 2014,
      typeTransport: 'Вантажні',
      typeBody: 'Бортова вантажівка',
      brand: 'MAN',
      mileage: '780 тис.',
   },
   {
      id: 16,
      name: 'Iveko dayli 2007 рік 3.0 дізель механіка',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/k6nmtx8f6u4v2-UA/image;s=1000x700',
      price: 7350,
      year: 2007,
      typeTransport: 'Вантажні',
      typeBody: 'Фургон',
      brand: 'Iveko',
      mileage: '370 тис.',
   },
   {
      id: 17,
      name: 'Mazda 3 1.6 Газ/Бензин',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/uucl41f761fd1-UA/image;s=1000x700',
      price: 2400,
      year: 2004,
      typeTransport: 'Легкові',
      typeBody: 'Хетчбек',
      brand: 'Mazda',
      mileage: '450 тис.',
   },
   {
      id: 18,
      name: 'Автомобіль Nissan rogue',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/kay4omr92izq3-UA/image;s=1000x700',
      price: 14200,
      year: 2016,
      typeTransport: 'Легкові',
      typeBody: 'Хетчбек',
      brand: 'Nissan',
      mileage: '322 тис.',
   },
   {
      id: 19,
      name: 'Тойота Камри 40 газ автомат',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/3t8pc4a3hkn81-UA/image;s=1000x700',
      price: 6000,
      year: 2007,
      typeTransport: 'Легкові',
      typeBody: 'Седан',
      brand: 'Toyota',
      mileage: '403 тис.',
   },
   {
      id: 20,
      name: 'Chevrolet Lacetti 1.8 газ/бензин',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/3t8pc4a3hkn81-UA/image;s=1000x700',
      price: 3800,
      year: 2005,
      typeTransport: 'Легкові',
      typeBody: 'Універсал',
      brand: 'Chevrolet',
      mileage: '122 тис.',
   },
   {
      id: 21,
      name: 'Nissan Almera Classic',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/oesr16edukql1-UA/image;s=1000x700',
      price: 3850,
      year: 2006,
      typeTransport: 'Легкові',
      typeBody: 'Седан',
      brand: 'Nissan',
      mileage: '270 тис.',
   },
   {
      id: 22,
      name: 'Chevrolet Aveo gbo-4',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/waanwh0khj2a-UA/image;s=1000x700',
      price: 2700,
      year: 2006,
      typeTransport: 'Легкові',
      typeBody: 'Хетчбек',
      brand: 'Chevrolet',
      mileage: '150 тис.',
   },
   {
      id: 23,
      name: 'Chery Tiggo 2.4 автомат',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/qz4pszv81ssn1-UA/image;s=1000x700',
      price: 3999,
      year: 2008,
      typeTransport: 'Легкові',
      typeBody: 'Позашляховик / Кроссовер',
      brand: 'Chevrolet',
      mileage: '170 тис.',
   },
   {
      id: 24,
      name: 'Богдан А-09202 2008г',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/kwl3srpjw3m23-UA/image;s=1000x700',
      price: 11000,
      year: 2008,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'Isuzu',
      mileage: '10 тис.',
   },
   {
      id: 25,
      name: 'Автобуси Тойота Caetano',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/tnbs8mp1cnlj3-UA/image;s=1000x700',
      price: 7200,
      year: 2000,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'Toyota',
      mileage: '350 тис.',
   },
   {
      id: 26,
      name: 'Автобуси Сканія К113',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/l6basb61d0vg3-UA/image;s=1000x700',
      price: 5500,
      year: 1997,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'Scania',
      mileage: '500 тис.',
   },
   {
      id: 27,
      name: 'Продам Автобуси .Man',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/mkj2n7lxttdl1-UA/image;s=1000x700',
      price: 5500,
      year: 1992,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'MAN',
      mileage: '500 тис.',
   },
   {
      id: 28,
      name: 'Мерседес спрінтер 314',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/8u42t94cmkig1-UA/image;s=1000x700',
      price: 19000,
      year: 2016,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'Mercedes',
      mileage: '357 тис.',
   },
   {
      id: 29,
      name: 'Автобуси є4',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/7xzacoqbmdfw1-UA/image;s=1000x700',
      price: 14500,
      year: 2008,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'Temsa',
      mileage: '580 тис.',
   },
   {
      id: 30,
      name: 'Автобуси шкільний ATAMAN D093S2',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/799f7mbjiaem1-UA/image;s=1000x700',
      price: 86700,
      year: 2025,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'Isuzu',
      mileage: '1 км',
   },
   {
      id: 31,
      name: 'Mercedes Sprinter 313 CDI Автобуси мікроАвтобуси',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/q3tlpct4uy293-UA/image;s=1000x700',
      price: 12700,
      year: 2001,
      typeTransport: 'Автобуси',
      typeBody: 'Пасажирський',
      brand: 'Mercedes',
      mileage: '255 тис.',
   },
   {
      id: 32,
      name: 'Lexus RX 300 ГБО',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/3amomq5c80ds3-UA/image;s=1000x700',
      price: 7450,
      year: 2004,
      typeTransport: 'Легкові',
      typeBody: 'Позашляховик / Кроссовер',
      brand: 'Lexus',
      mileage: '334 тис.',
   },
   {
      id: 33,
      name: 'Lexus LX 500d GINZA 2022',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/f3kfvdaltj1z1-UA/image;s=1000x700',
      price: 125000,
      year: 2022,
      typeTransport: 'Легкові',
      typeBody: 'Позашляховик / Кроссовер',
      brand: 'Lexus',
      mileage: '4000',
   },
   {
      id: 34,
      name: 'Lexus RX 300 ГБО',
      photo: 'https://ireland.apollo.olxcdn.com/v1/files/3amomq5c80ds3-UA/image;s=1000x700',
      price: 7450,
      year: 2004,
      typeTransport: 'Легкові',
      typeBody: 'Позашляховик / Кроссовер',
      brand: 'Lexus',
      mileage: '334 тис.',
   },
]